### ISSUE TITLE
What Does This Do?

### ISSUE THREAD

**Issue by DarwinJS** [Microsoft/msix-packaging#10]
Apologies if I missed a link somewhere - @joeyaiello and I were talking about this code and wondering what it's reason for being is.

If i am deducing correctly I think maybe it lets me unpack .appx and .msi on systems that do not support the regular apis for extracting these?  So Nano (MSI), Linux and OSX.  If that's true, do I then have to do my own install code for the extracted flies?

I guess my "issue" is needing some example use cases to help me understand the need for a cross platform subset of appx apis?

Thanks!

**Comment by RobCannon** [comment]
It look like the "support for Windows 7" is just this.  I was expecting to be able to install MSIX on Windows 7, but maybe without the isolation benefits.  I really want the ability for a Windows 7 user to be able to install with a similar experience to the Windows 10 user and get updates on launch.  We are starting to roll out Windows 10 in our Enterprise, but it will be years before that is complete.  So, we can't adopt this unless it work on Windows 7.

**Comment by aclinick** [comment]
We are working on a complete Windows 7 solution (i.e. you can install an MSIX on windows 7 with ARP, uinstall etc) but it's not here *yet*.  What is here is an MSIX package reader and manifest reader so you can use MSIX as a packaging format for your app.  For example, Office will be using MSIX as the packaging format for it's new addin format that runs on Windows, MacOS, iOS, Android and the web and they are using this exact code to enable that.

Question is what would you like for Linux and MacOS?

**Comment by DarwinJS** [comment]
For Linux my team is seeing more of the self-extracting bash installers.  Rapid7 is the latest example of a vendor packaging this way.  This avoids the need to make installers in multiple packager formats (yum for Fedora and apt-get for Debian).

Perhaps something similar?
Information: 
http://www.matteomattei.com/create-self-contained-installer-in-bash-that-extracts-archives-and-perform-actitions/
https://makeself.io/
