### ISSUE TITLE
[BUG] Crash when installing an MSIX

### ISSUE THREAD

**Issue by rido-min** [microsoft/msix-packaging#118]
I tried to install the next msix: 

https://wpfcoreapp.azurewebsites.net/CD/WpfCoreApp.Package_1.0.163.0_x86_Test/WpfCoreApp.Package_1.0.163.0_x86.msix

>Note the same MSIX can be installed with the default appinstaller after trusting the cert

but the install failed silently, and got the next error message from the EventViewer.

```
Faulting application name: MsixCoreInstaller.exe, version: 0.0.0.0, time stamp: 0x5ccc8258
Faulting module name: MsixCoreInstaller.exe, version: 0.0.0.0, time stamp: 0x5ccc8258
Exception code: 0xc0000005
Fault offset: 0x0000000000013891
Faulting process id: 0x1afc
Faulting application start time: 0x01d501f9e7ba63be
Faulting application path: C:\Program Files (x86)\Microsoft\MsixCoreInstaller\MsixCoreInstaller.exe
Faulting module path: C:\Program Files (x86)\Microsoft\MsixCoreInstaller\MsixCoreInstaller.exe
Report Id: f0f9518c-6a80-49c6-9679-b4e701283442
Faulting package full name: 
Faulting package-relative application ID: 
```
I would expect a better error message with UI.

**Comment by jvintzel** [comment]
This item should be resolved.  The link above is no longer valid.
