### ISSUE TITLE
Add WebAssembly compile target using emscripten

### ISSUE THREAD

**Issue by TheLarkInn** [Microsoft/msix-packaging#13]
Currently it looks as though this is written in C++ which could make it an excellent candidate to also be a host to compile to WebAssembly.

Why would you do that? Node.js v8 and up supports the loading of WebAssembly modules out of the box with no native bindings necessary. This means that you instantly provide every platform (back to Linux power PC) that NodeJS runs on as a candidate for using this library. 

Furthermore Web Application compiler/linker/packaging tools like webpack can use this capability for Desktop PWA's VSIX, ETC. 

😏

Can we support this as an MVP feature?

**Comment by msftphil** [comment]
It's a great idea, but I'm sure that if you have a PR in hand to enable a CMAKE switch to build this way (e.g. w/ CLANG), the suggestion would carry a LOT more weight.

**Comment by TheLarkInn** [comment]
Haha absolutely. I'm not the LLVM/CLANG/Emscriptem expert myself, so i'll do some digging!

**Comment by c-don** [comment]
Hi Sean - closed due to the inactivity. I will file a deliverable to track this work. Thanks.

**Comment by TheLarkInn** [comment]
Thanks considerably @c-don. This is pretty important if we continue down the path of msix as the universal UWP package format and being able to generate one via Node / Cross Plat.
