### ISSUE TITLE
[FEATURE REQUEST] Support for migration from ClickOnce

### ISSUE THREAD

**Issue by CMCjscarpace** [microsoft/msix-packaging#133]
MSIX should provide a mechanism to update software currently deployed using ClickOnce. This will save end users from having to uninstall a ClickOnce-deployed package and then install a MSIX-deployed package.

**Comment by samiranshah** [comment]
Hi @CMCjscarpace, sorry but this feature request is not relevant to the msix-packaging repository and we don't plan to implement it. So I'm closing the issue.
