### ISSUE TITLE
Use Git LFS?

### ISSUE THREAD

**Issue by wjk** [microsoft/msix-packaging#137]
**Project**  
MsixCore

**Describe the bug**  
When I tried to push the current master branch to my fork, GitHub warns that there are files (namely, the VLC MSIX files under preview\MsixCore\Tests) that are more than 50MB in size. GitHub recommends that [Git LFS](https://git-lfs.github.com) be used for files of this size. I don't know if this is practical or not. However, if it can be used, I would appreciate it, as these huge files take forever to download and upload (not to mention what they do to my 1TB Comcast monthly data cap…). Thanks!

**Comment by wcheng-msft** [comment]
Thanks for calling this to our attention. I've made the change to use git LFS for the msix and appx files under preview\MsixCore\Tests.

**Comment by JohnMcPMS** [comment]
#144
