### ISSUE TITLE
When do you plan to include MSIXCore in a windows 7 update?

### ISSUE THREAD

**Issue by urodolf** [microsoft/msix-packaging#141]
Hello, we want to deploy our products using msix packages and we have clients with windows 7 but we do not want to disturb them with additional packages installations. 
Our goal is that the client should not have administrator permissions as is currently done with ClickOnce.
When do you plan to include MSIXCore in a windows 7 update?

**Comment by jvintzel** [comment]
MSIX Core will not be a servicing update to Windows.  There will be an MSI That can be redistributed to enable MSIX via double-click or command-line installation.
