### ISSUE TITLE
[BUG] Cant run installer in vs 2019 for SDK based projects for .net framework applications

### ISSUE THREAD

**Issue by jmecosta** [microsoft/msix-packaging#165]
*Project*
Using Visual studio 2019 and trying to package a win32 application using new SDK based project and target .net framework 4.7.2 or 4.8

**Describe the bug**
Cant compile, msix gets with .net core targets
1>------ Build started: Project: WpfApp1SDK, Configuration: Debug Any CPU ------
1>C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
1>WpfApp1SDK -> E:\prod\tools\BuildTools\buildallextension - Copy\WpfApp1SDK\bin\Debug\net48\WpfApp1SDK.exe
2>------ Build started: Project: TafApp.Installer, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1653,5): error : Project '..\WpfApp1SDK\WpfApp1SDK.csproj' targets 'net48'. It cannot be referenced by a project that targets '.NETCore,Version=v5.0'.
2>Done building project "TafApp.Installer.wapproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**To Reproduce**
Seem solution in attachmentn

By the way, using PackageReference in old csproj format does not cause a problem, only the new sdk based projects do. 

Any workaround i can used besides going back to previous project type?

thanks

**Comment by jmecosta** [comment]
[BuildAllExtension.zip](https://github.com/microsoft/msix-packaging/files/3349533/BuildAllExtension.zip)

**Comment by mslucyyloo22** [comment]
Hi,
Thanks for your message. Are you trying to package your own application? Visual Studio 2019 supports packaging and you may not need the csproj file if that's the case?

**Comment by jmecosta** [comment]
@mslucyyloo22  thanks for the reply, trying to follow https://mybuild.techcommunity.microsoft.com/sessions/77012?source=sessions#top-anchor if i use a old project style that all that works just fine. if i convert the project to new sdk based project the windows app project no longer works.  the zip in attachmetn you can see it

**Comment by jacargentina** [comment]
I've solved a similar problem (error from `Microsoft.Common.CurrentVersion.targets(1653)`) by using [`<SetTargetFramework />`](https://stackoverflow.com/questions/56757649/how-to-fix-target-framework-reference-for-windows-application-pack-in-visual-stu) on each referenced project

**Comment by sbanni** [comment]
Hello, you need to add this property to your ProjectReference in the .wapproj:
    <ProjectReference Include="..\WpfApp1SDK\WpfApp1SDK.csproj" >
      <SkipGetTargetFrameworkProperties>True</SkipGetTargetFrameworkProperties>
    </ProjectReference>

You can see that the .wapproj does this automatically for you when referencing a .netcore project.

**Comment by jvintzel** [comment]
based on comments this thread looks to be resolved with sbanni's feedback.

**Comment by jmecosta** [comment]
@jvintzel setting SkipGetTargetFrameworkProperties solves the issue, however i think this still be adressed. If you have a net48 target app and create a installer project and add a project reference  SkipGetTargetFrameworkProperties  will not be set and it will fail by default...

i dont think this is the correct behaviour, the correct behaviour for a net48 when you add a project reference the project should build without user changing a flag in the project file.
