### ISSUE TITLE
[BUG] libcef fails to load in UWP Win32 application

### ISSUE THREAD

**Issue by jmecosta** [microsoft/msix-packaging#166]
MSIX SDK 

**Describe the bug**
Chromium.CfxException: 'Unable to load libcef library E:\prod\tools\BuildTools\buildallextension\TafApp.Installer\bin\x64\Debug\AppX\TafApp\cef64\Release\libcef.dll'

**To Reproduce**
build a cef application and try to deploy to Windows 10

Its not related with x64 vs x86, both have problems.  How can i force load those native dlls?

thanks

**Comment by msftrubengu** [comment]
How are you building your application? Is it using Visual Studio? 

I don't believe this issue is related to the MSIX SDK. The MSIX SDK allows you to unpack an MSIX package on multiple platforms. It doesn't do any deployment.

**Comment by jmecosta** [comment]
yep, its related with UWP. just trying to see if could get some idea on how to use cef in UWP
