### ISSUE TITLE
Linux differentiation

### ISSUE THREAD

**Issue by lkmcdo** [Microsoft/msix-packaging#17]
Would appreciate differentiation of Linux platforms. Howabout for starters, glibc versus self-provided (musl, etc.)? Console vs X11 vs Wayland would also be valuable.

I don't have total insight as to how to further differentiate but these seem like a few vital bits of information.

**Comment by msftrubengu** [comment]
We build and test internally on Ubuntu 16.04.3 LTS using clang++ version 5.0.0

libmsix.so is the core of the MSIX SDK. makemsix is a console application that unpacks an MSIX package via libmsix.so

It would be interesting to experiment using different STL implementations.
