### ISSUE TITLE
Error: 80070002 while extracting

### ISSUE THREAD

**Issue by charlesxsh** [Microsoft/msix-packaging#18]
Meet "Error: 80070002 while extracting the appx package" when using "ExtractContentsSample.exe -ss -sv -mv -p abcde.msix -d abcde".
Platform: Windows10 x64
VS2017

**Comment by msftrubengu** [comment]
It is likely that there is a mismatch between the files described in the BlockMap and the OPC container of your msix package. Can you try running "makemsix.exe unpack -ss -sv -mv -p abcde.msix -d abcde" and post the output?

Please do "mkdir abcde" before running makemsix. There is a known issue where makemsix doesn't create the output directory. That will be included in a future release.

**Comment by charlesxsh** [comment]
@msftrubengu You are right. I run msix exmaple using vs debug and double check it is a mismatch between blockmap and content in package. Probably that file hasn't flush out from buffer when capturing.
