### ISSUE TITLE
Incorrect team-email to send questions

### ISSUE THREAD

**Issue by amalabey** [microsoft/msix-packaging#206]
*Project*
MSIX SDK or Win7Msix

**Describe the bug**
The email address "mailto:MSIXPackagingOSSCustomerQs@service.microsoft.com" does not work. I had some questions and sent an email to above address as per the README, but the email bounced back.

Appreciate if you could either answer below questions or provide an alternative way (e.g. forum) to ask these questions:

We have a product that needs to support installation in a consumer scenario where our customers (few thousands) are using Windows 7 SP1, Windows 8.1 and many versions of Windows 10. Our main intention of looking into MSIX is its ability to auto-update (like Chrome does) and we realized official auto-update support is only available on Windows 10 1803 onwards. Can you help me understand below with regard to MSIX Core,

1.	Can we still auto-update the package on Windows versions prior to Win 10 1803 using MSIX Core? If so , please send us some links to corresponding documentation.
2.	Can we programmatically control (e.g. web url to look for updates) auto-updates using MSIX SDK? Please share some documentation
3.	When will MSIX Core come out of preview? Can you share your roadmap including if you plan to enable support for above #1, #2 in the future.
4.	Does the MSI package produced by MSIX Core (1) enable MSIX support so in the future MSIX packages can be installed by double-clicking? (2) deploys the MSIX package behind the scenes? Or both?

**Comment by jvintzel** [comment]
1/2) Auto-updating for MSIX core is on the roadmap, but not yet scheduled.  
3) For developers, they can consume the libraries today.  The MSI will be out of preview later this year.
4) deploying the MSI redistributable will allow double-click installs of MSIX as well as command-line automation.

**Comment by amalabey** [comment]
Thanks for the response.

**Comment by jvintzel** [comment]
closing issue
