### ISSUE TITLE
msixmgr installer UI does not display the package name

### ISSUE THREAD

**Issue by GITNE** [microsoft/msix-packaging#231]
# Project #
MSIXCore msixmgr

## Describe the bug ##
The msixmgr installer UI *MSIX Installer* displays the `DisplayName` of the first `Application` (only) in the package instead of the package name (the package's `DisplayName` property). Users expect to see the package name here. Applications, if any, are detail information about a package. Resource only packages do not have to have an application and therefore msixmgr fails on resource packages completely.

## Expected behavior ##
msixmgr's installer UI should display the packages name (the package's `DisplayName` property).

## Platform ##
Windows 7 and later

**Comment by jvintzel** [comment]
Thanks for the feedback, we are looking into fixing the item.
