### ISSUE TITLE
MSIX installer for Win7 produces incorrect start menu shortcuts

### ISSUE THREAD

**Issue by rido-min** [Microsoft/msix-packaging#26]
I've created a simple package using the VS packaging project, I selected the lower TPMinV (14393) and generated an APPX.

When installing with the Win7MSIXInstaller the start menu shortcut  point to a non existing path.

Shortcut path: `C:\Program Files (x86)\WindowsApps\MyConsoleApp\ConsoleApp8\ConsoleApp8.exe`
App deployed to: `C:\Program Files (x86)\WindowsApps\cc2f422a-da02-40aa-8689-9541e0255135_1.0.0.0_neutral__2veb5pcjw4wx2\ConsoleApp8\ConsoleApp8.exe`

**Comment by msftrubengu** [comment]
This is a bug. Win7MSIXIntaller.cpp:432 should be
`std::string filePath = "C:\\ProgramData\\Microsoft\\Windows\\Start Menu\\Programs\\" + utf16_to_utf8(packageFullName) + ".lnk";` not displayNameString

**Comment by rido-min** [comment]
@c-don is this fixed? can you point to the updated source and/or binaries?

**Comment by c-don** [comment]
We are tracking the bug internally and will be fixed in a future update of the SDK.

**Comment by wcheng-msft** [comment]
The most recent push should have fixed this.

**Comment by rido-min** [comment]
Hi @wcheng-msft  I tried to install the latest release from https://github.com/Microsoft/msix-packaging/releases/tag/Win7MsixInstaller-preview 

But now: 1) I don't have the AppInstallApp UI anymore (is this a CLI tool only?) and 2) AddPackage command fails with: 

`Failed to process request 8bad0043`

>IMHO issues  should remain open until the  one who created the issue can verify it's fixed

**Comment by msftrubengu** [comment]
0x8bad0043 is MSIX::Error::PublisherMismatch which means the publisher that signed the package doesn't match the publisher from the identity element of the AppxManifest.xml.

I am not sure if the Win7Msix dumps the MSIX SDK logs, but if it doesn't you can try building and running makemsix unpack -p <your package> -d <directory output> and you would see something like:
```
Microsoft (R) makemsix version 1.6.49
Copyright (C) 2017 Microsoft.  All rights reserved.
Error: 8bad0043
LOG:

Publisher mismatch: <some publisher> != <another publisher>
Call failed in D:\a\1\s\src\msix\AppxPackageObject.cpp on line 137
```

**Comment by wcheng-msft** [comment]
There is a bug in that the UI doesn't show if the package doesn't open. The error-case handling was broken with the recent changes.

**Comment by ridomin** [comment]
@msftrubengu how can I get `makemsix` to run unpack?

I've tried with packages that I can install with the AppInstallApp or Add-AppxPackage, so I dont think this is due to a publisher mismatch.

Can you re-open this issue until we can verify it has been fixed in a public release?

**Comment by msftrubengu** [comment]
makemsix is a command line utility that you need to build. Easiest way to build it is using makewin.cmd
