### ISSUE TITLE
Where to find MSIXCoreInstaller?

### ISSUE THREAD

**Issue by AR1ES** [microsoft/msix-packaging#265]
I developed the application and packaged it in msix. Now I want to try installing it on Win7. But I can not find any executable files and usage materials.

**Comment by jvintzel** [comment]
It's in preview under releases:  https://github.com/microsoft/msix-packaging/releases 

You can download msixmgr.msi to deploy.  Readme here: https://github.com/microsoft/msix-packaging/tree/master/preview/MsixCore
