### ISSUE TITLE
Win7 MSIX installer does not validate signature

### ISSUE THREAD

**Issue by rido-min** [Microsoft/msix-packaging#27]
The Win10 Appinstaller requires to trust the certificated used for signing, but the Win7 version allows to install packages from untrusted signers

**Comment by msftrubengu** [comment]
The Win7MSIXInstaller is a preview, because of that the Win7MSIXInstaller pass the MSIX_VALIDATION_OPTION::MSIX_VALIDATION_OPTION_SKIPSIGNATURE flag to CoCreateAppxFactoryWithHeap. The MSIX SDK skips signature validation for packages when this flag is used.

**Comment by rido-min** [comment]
Is there any config setting to enable signature validation? Any ETA to enable the validation by default?

**Comment by msftrubengu** [comment]
For the installer, as an experiment, removing the [g_state.SkipSignature() call](https://github.com/Microsoft/msix-packaging/blob/9775952287134d56de77b23ea0bb08101ad2351f/preview/Win7Msix/Win7MSIXInstaller/Win7MSIXInstaller.cpp#L499) will result on using the MSIX_VALIDATION_OPTION::MSIX_VALIDATION_OPTION_FULL flag.
The MSIX_VALIDATION_OPTION flags are defined [here](https://github.com/Microsoft/msix-packaging/blob/9775952287134d56de77b23ea0bb08101ad2351f/src/inc/AppxPackaging.hpp#L1230).

**Comment by c-don** [comment]
Regarding allowing signature check by default, we want to allow the developers to decide that. We strongly recommend that all apps that take a dependency on the SDK to enable that. At the same time, we want to allow the host apps to make that choice for their ecosystem. 
I closed it assuming the above answer from msftrubengu was satisfactory.

**Comment by ridomin** [comment]
IMHO this issue should not be closed until the feature has been released (or at least merged in a production branch),
