### ISSUE TITLE
Windows Server support

### ISSUE THREAD

**Issue by AsciiWolf** [microsoft/msix-packaging#273]
Are there any plans to support MSIX on server Windows OSes?

**Comment by AsciiWolf** [comment]
Oops, please remove the "bug" label that I accidentally added. This is a feature request, not a bug report.

**Comment by JohnMcPMS** [comment]
Is the request to support MSIX via OS based deployment APIs, or to support it via this cross-platform SDK?

**Comment by AsciiWolf** [comment]
I meant out-of-box support for installing MSIX packages on Windows Server 2019 the same way as it is currently supported on client Windows OSes. Or at least after installing MSIX Core.

**Comment by wcheng-msft** [comment]
Yes, for MSIX core,  specify MSIXCore.Server in the manifest and it should deploy on Server.

**Comment by jvintzel** [comment]
Windows Server with a GUI is supported with the correct manifest entries.

**Comment by AsciiWolf** [comment]
Thanks, I didn't know it is already supported. It would be nice if it was mentioned on [MSIX](https://docs.microsoft.com/en-us/windows/msix/overview) or [MSIX Core](https://docs.microsoft.com/en-us/windows/msix/msix-sdk/msixcore) page.
