### ISSUE TITLE
MSIX Required Properities List

### ISSUE THREAD

**Issue by Smorgan05** [Microsoft/msix-packaging#28]
I was pointed over here by OneGet and I was wondering what the required properties list is for MSIX applications.  I was not able to locate this on the MSIX Documentation page.  Is it the same as MSI? Does it have better standards?

Thanks.

**Comment by Smorgan05** [comment]
Chaitanya,

When I attempted to install the MSIX Packaging Tool from the Windows Store it stated that it was not there.  Most of my questions would be answered by converting an MSI to an MSIX and then monitoring how it writes information to the registry and so forth.  Also is there a debugging mode for msix? I know with msis you can debug during the installation (this would be great):

msiexec /i  yourfile.msi /L*v  c:\temp\yourinstall.log

Thanks,
Morgan

**Comment by c-don** [comment]
Hi Morgan, 
MSIX packaging tool requires you to be running Windows 1809 or later and few more prerequisites as listed [here](https://docs.microsoft.com/en-us/windows/msix/mpt-overview#prerequisites). 

To get debug logs:
You can install the msix package using the PowerShell cmdlet - ['Add-AppxPackage'](https://docs.microsoft.com/en-us/powershell/module/appx/add-appxpackage?view=win10-ps) and then use [Get-AppxLog](https://docs.microsoft.com/en-us/powershell/module/appx/get-appxlog?view=win10-ps) to view the logs. Provide the activity id that you get from the output of the Add-AppxPackage cmdlet run. 

If you have more questions regarding the tool, please post them in the [MSIX packaging tool article page](https://docs.microsoft.com/en-us/windows/msix/mpt-overview#prerequisites). 

Thanks,
Chaitanya

**Comment by Smorgan05** [comment]
Chaitanya,

Much Appreciated on the quick and informative response! I'll spin up a VM and take a look.

Thanks,
Morgan
