### ISSUE TITLE
Source code for checked-in binaries?

### ISSUE THREAD

**Issue by wjk** [microsoft/msix-packaging#280]
**Project**  
MSIX Core

**Describe the bug**  
There are several pre-built binaries in this repository with no corresponding source code. Would it be possible to remedy this? From inspecting the copy of ApplyACLs.dll in this repository, I see that it is built out of the OS repo. Is there any reason why this DLL is so dependent on proprietary Windows code? Can't ACLs be applied by using public APIs? If this file cannot be open-sourced, would it at least be possible to document at a high level what ACLs it applies?

Personally, I find it endlessly irritating when Microsoft releases "open-source" code that has hard dependencies on closed-source files. (WPF is one such example; the sources for `PresentationNative_cor3.dll` will not be released, making it nearly impossible for anyone outside of Microsoft to refactor the WPF functionality that depends on this file.)

On a related issue, I have never figured out how to properly create MUI localization files for a project that is localized for more than one language due to a lack of both documentation and examples. If the RC files and build scripts for the MUI files could be published, I would appreciate it. Thanks!

**Comment by wcheng-msft** [comment]
See https://docs.microsoft.com/en-us/windows/win32/intl/creating-a-multilingual-user-interface-application for creating MUI files. 

We have a post-build script in the msixmgr project (https://github.com/microsoft/msix-packaging/blob/master/preview/MsixCore/msixmgr/msixmgr.vcxproj), but we send our english MUI file to a localization service to generate other language files.
The RC file is in the same folder (msixmgr.rc)

As for ApplyACLs.dll, this functionality is not used in the win7 scenario. @stephenk-msft can expand more on what it does and what it's used for.

**Comment by jvintzel** [comment]
msixmgr is also used to stage the vhdx for MSIX app attach.  ApplyACLs.dll is required for the vhdx setup.
