### ISSUE TITLE
Project is dead ? no updates for 3 months

### ISSUE THREAD

**Issue by gedw99** [Microsoft/msix-packaging#29]
The idea behind this project is great. I am so sick off the crappy packaging experience.

1. Is this dead ? why no updates in ages ?

2. Doe it really allow packaging apps for other desktops and mobiles. If so i presume it matches teh format and binary encoding of what those OS'es expect natively ? 

3. Following on from 3, then this means i can package any app i wrote. It does not have to be a windows app written in c# ?

thanks again.

**Comment by c-don** [comment]
Hi gedw99, 
This project is not dead. We are continuing to add functionality to the SDK. We are currently accessing where our investments should lie. 

Few clarifications: 
- You can use the Windows SDK(MakeAppx) to package your app contents into an MSIX package. If you have an existing windows app(.msi, .exe etc), you can use the MSIX packaging tool to package it as a MSIX package. More info can be found [here](https://docs.microsoft.com/en-us/windows/msix/mpt-overview)
- The SDK allows you to extract contents from an MSIX package regardless of the platform. 
- It can package any app and doesn't need to be a windows app. Though on Win10, you wont be get the benefits of Windows 10 deployment if you are not packaging a Win10 app. 
- If you are looking to package app contents and construct your app manifest file to target the specific platforms, you can use the MakeAppx.exe found in the Win10 SDK to package and use the MSIX SDK from this project to extract the package contents. 

Thanks
