### ISSUE TITLE
Will packaging sdk support msix package creation?

### ISSUE THREAD

**Issue by peitaosu** [Microsoft/msix-packaging#30]
I know makeAppx.exe from Windows SDK can do it. I just wondering will this project also support package/bundle creation since it's already support package/bundle unpack? Any thought?

**Comment by c-don** [comment]
We have that item in our backlog. It would be great if you can comment on how you plan to use the package creation support in your environment. This info would help us focus our efforts on features that our customers will benefits from.

**Comment by peitaosu** [comment]
Thank you @c-don ! I am so interested to try this new tech on macOS/Linux. Use msix to pack and unpack my application, and also adopt the update mechanism (blockmap) to benefits application update.
Since this project is open source, will you consider to share the backlog/plan in github?
