### ISSUE TITLE
Not that well written

### ISSUE THREAD

**Issue by StealthStalker** [Microsoft/msix-packaging#31]
If your going to write technical articles please be more clear.

**Comment by c-don** [comment]
Hi @StealthStalker - thanks for your feedback. Can you specify what you would like to learn more about. We will modify the articles to be more clear.

**Comment by StealthStalker** [comment]
I can't even find the article non so this whole platform is a mess.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by StealthStalker** [comment]
> Hi @StealthStalker - thanks for your feedback. Can you specify what you would like to learn more about. We will modify the articles to be more clear.

I can't even find the article non so this whole platform is a mess.

**Comment by c-don** [comment]
Let us know if there is specific information that you are looking for, that we can clarify. Going forward, we are going to do our best to have our documentation more clear.
