### ISSUE TITLE
Add more manifest schemas to repo?

### ISSUE THREAD

**Issue by wjk** [Microsoft/msix-packaging#32]
I noticed that the manifest schema resources stop at the end of 2017. Is there any chance that the new MSIX manifest schemas from Windows 10, 1803, 1809, and 19H1 (when they're ready, for that last one) can be added to this repository? I find this is the most convenient place to reference AppX/MSIX schema details. Thanks!

**Comment by msftrubengu** [comment]
We will update the schemas when 19H1 ships

**Comment by msftrubengu** [comment]
Schemas added as of PR #82.
