### ISSUE TITLE
Installing Appx via msixmgr.exe requires admin permissions on Windows 7

### ISSUE THREAD

**Issue by greenmooseSE** [microsoft/msix-packaging#326]
**Project**
Win7Msix

**Describe the bug**
When I try to install an appx package on Windows 7 Pro SP1 (via msimgr -AddPackage our via dbl click on appx), Win7 is asking for admin privileges.
Version: 6.1 (Build 7601: service Pack 1)

**To Reproduce**
1. Install [msixmgr](https://github.com/microsoft/msix-packaging/releases/tag/MSIX-Core-1.1-release) with an admin account (I installed via the x64 msi).
1. Login with a non-admin user account (FWIW, my win7 did not merge the system PATH env. variable so I had to update user's PATH manually).
1. Try to install the appx package.

**Expected behavior**
The application to be installed without admin privileges.

**Screenshots**
![image](https://user-images.githubusercontent.com/31244330/71990992-b08de980-3234-11ea-8de8-7346cefdbdab.png)

**Platform**
Windows Version: 6.1 (Build 7601: service Pack 1)

**Additional context**

**Comment by wcheng-msft** [comment]
This is by design; we should probably update the readme and associated documentation to be clearer on this. For msixmgr, because we do not have container support from the OS, the registry and files associated with a package are written to the corresponding locations in the OS; most of these locations require admin privileges. Thus, we decided to require admin privileges for msixmgr.exe install these packages on windows 7.

**Comment by greenmooseSE** [comment]
Ok thanks, maybe we need to look for another solution then.

Our problem is this:
We have users using both win10 and win7 (with users not having admin rights). This is a server/client app and the client app versions need to match the server versions (depending which server the user logs in to via the client app). Our first idea was to use Msix and then when user starts the app, it determines which server it should connect to, ensure that correct client version is installed (somehow), and if not install the correct version automatically (without admin rights) and start it.

I had the impression that this, at least with win10, could be solved via Msix and using the APIs to check for available versions and upgrade/downgrade as needed (programatically), making the user experience as smooth as possible.

Do you think I am on a dead end here and need to rethink to instead have separate install solutions for win10 and win7 clients? Maybe Msix is not suitable for above scenario at all (and instead use a separate launcher app which decides which msi to install for instance)? 

Thanks.

**Comment by wcheng-msft** [comment]
Msixmgr currently does not support force-downgrading to lower versions on Windows 7 either.

MSIX does allow it on Windows 10, but I think for your scenario, the best solution is to get all the servers on the same version. Assuming that's not possible, a better solution is to split your client app into multiple apps-- app A that connects to the server, and app B that launches app A. Allow the app A client installs to be side by side by naming each version differently; and then app B client "manager/launcher" app that allows user to select which server and correspondingly selects which of the app A to launch. That way you wouldn't have to repeatedly upgrade/downgrade if users wants to switch servers frequently.

**Comment by greenmooseSE** [comment]
Yeah I think that is the route we will end up with (1 app launcher and X client apps). Thank you for your input!
