### ISSUE TITLE
Consider allowing self-signed certificates in App Installer

### ISSUE THREAD

**Issue by wjk** [microsoft/msix-packaging#332]
One of the biggest pain points for me with MSIX currently is how the App Installer requires that MSIX packages be signed with a commercially obtained code-signing certificate. In my opinion, this completely precludes small development shops like mine from providing MSIX packages directly to users due to the extremely high cost of the required cert. (Furthermore, I understand that it is CA policy to only issue code-signing certs to legal entities, and never to individuals. This adds even more expense and complexity, as I do not want to incorporate or form an LLC due to the complicated tax situation doing so would subject me to.) I am therefore forced to wrap the MSIX in an EXE-based installer that adds the self-signed certificate I use to the Trusted People store, then calls the deployment APIs to perform the actual installation. This is rather inconvenient, and it also means I can't use the App Installer's auto-update check feature.

In all honesty, the fact that a certificate is issues by a commercial CA provides no extra value to the question of if the package is trustable. The purpose of code signing on Windows is to validate that the binaries I have are the same binaries that the developer released, and that they haven't been tampered with since. To confirm this, I can compare the the thumbprint of the certificate to what the publisher specifies. If they are the same, then I can be as certain as I can be that the binaries were signed by who I think they were. This process works just as well for self-signed certs as for commercial certs. (Not to mention, there have been many incidents wherein commercial CAs have issued certs that were then used fraudulently or used to sign malware, rendering the validation process of getting a cert worthless IMO.)

I remember seeing a Windows 2000-era screenshot of the ActiveX control installer that included verbiage like "[publisher name] represents that this content is safe. Only install if you trust [publisher name] to make this assertion," along with a button to view the certificate details. _This_ is how code signing should work, and is in fact how it does work on Linux. Would it be possible to update the App Installer to show a similar dialog if a self-signed certificate is detected, and auto-install the certificate if the user consents? (If the cert used is commercially signed, no warning need appear and the behavior doesn't need to change.) This is especially important on Windows 10X, where MSIX packages are the preferred method of deploying applications. Thanks!

**Comment by wjk** [comment]
I have since found a commercial CA that both (a) charges reasonable prices for their certificates, and (b) issues code signing certs to individuals like me. (For the benefit of those who find this issue in the future, the CA I am referring to is [SSL.com](https://www.ssl.com/certificates/code-signing/).) Since this issue is no longer relevant to me (and very unlikely to be acted upon in the first place, I'm going to close it now. Thanks!

**Comment by nephatrine** [comment]
For the benefit of anyone who stumbles on this closed issue, I just want to chime in that what I do is use a self-signed certificate and provide the public .crt alongside my downloads and users just have to add it if they trust me as source and are able to install my appx/msix packages without issue afterwards. Sure, it's slightly more effort for an end-user than it just working out of the box or automatically asking to add the certificate, but it's not terribly difficult and only needs to be done once (at least until the cert expires).

**Comment by minusium** [comment]
It's ridicules, You can run any win32 apps with full privilege, even if they're not signed, but you can't run secure MSIX apps in a container without a trusted certificate.

**Comment by steam3d** [comment]
@xmine64 I agree.  What's the point of choosing msix in development if there are so many restrictions?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/msix-packaging/issues/332#issuecomment-2158068282

I presume that [`stackoverflow.com/q/23812471`](https://stackoverflow.com/q/23812471/9731176) applies to MSIX packages too. Perhaps follow it.

**Comment by iqnite** [comment]
Why is this closed as "Resolved"? The described issue is still around in 2025!

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/msix-packaging/issues/332#issuecomment-2997298375

@iqnite, GitHub didn't provide a way to close as unplanned / invalid when this was closed. It should be reopened, though.

**Comment by iqnite** [comment]
For those who are still looking for a workaround, the solution I've found is to make a PowerShell script (wrapped in an EXE) that first installs the certificate and then runs the MSIX. It's not clean, and it will probably trigger an antivirus warning, but at least it works.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/msix-packaging/issues/332#issuecomment-2997838567

@iqnite, I'd use that. All the user has to do is run a PowerShell script, instead of the MSIX file. Heck, Chocolatey is entirely PowerShell-based, so it's not unprecedented. Is it available online, like in a Git repository?

**Comment by iqnite** [comment]
> [@iqnite](https://github.com/iqnite), I'd use that. All the user has to do is run a PowerShell script, instead of the MSIX file. Heck, Chocolatey is entirely PowerShell-based, so it's not unprecedented. Is it available online, like in a Git repository?

Not yet, I'll release it tomorrow. I'll notify you!

**Comment by iqnite** [comment]
@RokeJulianLockhart here: https://github.com/iqnite/msix-no-cert

Let me know if it works! If you encounter any problems, please create an issue on the repo.

**Comment by PeteJobi** [comment]
> For those who are still looking for a workaround, the solution I've found is to make a PowerShell script (wrapped in an EXE) that first installs the certificate and then runs the MSIX. It's not clean, and it will probably trigger an antivirus warning, but at least it works.

Has it been confirmed that this will trigger an antivirus warning?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/msix-packaging/issues/332#issuecomment-3021179249

@PeteJobi, you should have asked this at the linked repository. Additionally, unless you state which:

1. AV and
2. message

...you refer to, that's impossible to answer, for some AVs are configured to prompt upon user innovation of any executable file, whereas some might prompt due to its behaviour, to prevent polymorphic malware that it's misidentified the script as.

Better yet, why do you ask this?

**Comment by PeteJobi** [comment]
> > [#332 (comment)](https://github.com/microsoft/msix-packaging/issues/332#issuecomment-3021179249)
> 
> [@PeteJobi](https://github.com/PeteJobi), you should have asked this at the linked repository. Additionally, unless you state which:
> 
> 1. AV and
> 2. message
> 
> ...you refer to, that's impossible to answer, for some AVs are configured to prompt upon user innovation of any executable file, whereas some might prompt due to its behaviour, to prevent polymorphic malware that it's misidentified the script as.
> 
> Better yet, why do you ask this?

My bad, I posted that comment before I saw the link. I asked because it would be the perfect convenient way to install the certificate for the user if it didn't trigger any AV warnings. But I understand why it does. 

In any case, I decided to bundle the package with the certificate in the release on my [repo](https://github.com/PeteJobi/MediaTrackMixer), for the users to install manually. If users don't want to do that, there is the option to build it themselves as an unpackaged app. I'm going to check out that no-cert repo in a bit.

**Comment by beedell-roke** [comment]
[`WindowsAppSDK/issues/128`](https://github.com/microsoft/WindowsAppSDK/issues/128#issue-665626455) and [`qbittorrent/qBittorrent/issues/18028#issuecomment-1436046285`](https://github.com/qbittorrent/qBittorrent/issues/18028#issuecomment-1436046285) may be of use.

**Comment by iqnite** [comment]
I know this is late, but the Microsoft Store now provides free registration to individuals: https://blogs.windows.com/windowsdeveloper/2025/09/10/free-developer-registration-for-individual-developers-on-microsoft-store/

I'm distributing my app through it and haven't had any issues so far.
