### ISSUE TITLE
Package size is large. Can external deps be downloaded at install time?

### ISSUE THREAD

**Issue by virzak** [microsoft/msix-packaging#338]
The project I'm working on currently uses WiX ToolSet to create an MSI and then Bundle it.

MSI contains the .Net Core Desktop app and the bundle contains URLs for dependencies: SQL Server LocalDB and .Net Core Runtime for Desktop.

Since the .Net Core Desktop app is not compiled as a standalone project and the dependencies are not included in the bundle, but are downloaded at installation time, the size of the installation is under 10 MB. Package size becomes 60MB just for a minimal XAML Islands [sample](https://github.com/microsoft/Xaml-Islands-Samples/blob/master/Samples/WinForms/WAP/WAP.wapproj)

Switching to MSIX, it seems that the installation must contain all Framework dependencies and not even sure if there is a way to install LocalDB from [here](https://download.microsoft.com/download/E/F/2/EF23C21D-7860-4F05-88CE-39AA114B014B/SqlLocalDB.msi).

Is there anything that can be done to reduce the package size?

**Comment by samiranshah** [comment]
Hi @virzak, could you please clarify your question? 
Assuming that packages exist for everything you've listed, then a .appinstaller file would be similar to what you have in an MSI. https://docs.microsoft.com/en-us/windows/msix/app-installer/app-installer-file-overview

**Comment by virzak** [comment]
@samiranshah will try to clarify in reverse order

## Dependencies

The software I am trying to install depends on [SqlLocalDB.msi](https://download.microsoft.com/download/E/F/2/EF23C21D-7860-4F05-88CE-39AA114B014B/SqlLocalDB.msi). It is possible to add it at install time using [\<Dependencies>](https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-dependencies) (or another) node? It doesn't look like it has ever been added to any [.appinstaller](https://github.com/search?q=msi+extension%3Aappinstaller&type=code) file as of now.

## Framework-dependent installation

When [XAML Islands sample](https://github.com/microsoft/Xaml-Islands-Samples/blob/master/Samples/WinForms/WAP/WAP.wapproj) is published, the MSIX archive contains large assemblies (PresentatioFramework.dll in the image below), which are part of [.NET Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/5.0). It makes the MSIX unnecessarily large instead of being able to just ensure that the framework is installed. Perhaps @marb2000 can weigh in?

![image](https://user-images.githubusercontent.com/6209775/107883270-fe573580-6ebb-11eb-8411-ccfefcbabeed.png)

**Comment by JohnMcPMS** [comment]
AppInstaller files do not support unpackaged dependencies like and MSI.  I can't really speak to any history or reasoning behind the .Net assemblies being that or any package.

**Comment by virzak** [comment]
@JohnMcPMS any suggestion on using MSIX with MSI dependencies at all? Perhaps through a custom script? Or having an MSI dependency us a showstopper for MSIX?

**Comment by JohnMcPMS** [comment]
There is some form of custom action support in MSIX, although it is limited.  I'm not very familiar with it though.  You might be able to leverage that to retrieve files from outside of the package.

Have you tried any of the options here?
https://docs.microsoft.com/en-us/windows/msix/packaging-tool/create-an-msix-overview

**Comment by samiranshah** [comment]
@virzak you could provide feedback to the Visual Studio here and file an item to package .Net assemblies https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options?view=vs-2019

**Comment by virzak** [comment]
@samiranshah the questions have nothing to with Visual Studio or any other IDE.

I appreciate that when .Net 5 or another target framework gets packaged into MSIX, that should probably be asked at https://github.com/dotnet/runtime.

However MSI and EXE prerequisites should be addressed in the "samples" folder of this repo, IMO. That's unless achieving that with MSIX is currently unattainable and there is no plan on providing this feature. If that's the case this issue should be closed.

There are lots of opensource projects on [GitHub](https://github.com/search?q=OutputType+bundle+extension%3Awixproj)  which use [WiX bundles](https://wixtoolset.org/documentation/manual/v3/bundle/), which achieves exactly that - install prerequisite or dependency prior to the main product installation.

**Comment by anarvekar-msft** [comment]
> AppInstaller files do not support unpackaged dependencies like and MSI. I can't really speak to any history or reasoning behind the .Net assemblies being that or any package.
