### ISSUE TITLE
Access is denied when running cli tool bundled with an application

### ISSUE THREAD

**Issue by yaichenbaum** [microsoft/msix-packaging#339]
**Describe the bug**
I am trying to create an MSIX installer for an Electron app. The app includes a cli tool that is required for the apps functionality. The issue I am running into is that when the app tries launching the cli tool, it returns an "Access is denied" error. If I install the application with a regular exe installer, the cli tool launches just fine.
I am wondering if there is a capability that I need to add, or if this setup isn't possible with MSIX packages.

**Comment by yaichenbaum** [comment]
@jvintzel Is there any update? I opened this issue a couple months ago and there hasn't been any response.

**Comment by samiranshah** [comment]
Hi @yaichenbaum, can you provide more information about the app? Is it a Centennial app or a UWP app?
Is this what you are trying to do? https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.FullTrustProcessLauncher?view=winrt-19041

**Comment by yaichenbaum** [comment]
@samiranshah It's an Electron app so I guess it would be Centennial.

**Comment by samiranshah** [comment]
Hi @yaichenbaum, could you share your AppxManifest? It is possible that the cli tool your app is trying to run will end up breaking the security of the app container, and so it is being denied access.

**Comment by yaichenbaum** [comment]
@samiranshah The cli tool does seem to break the security of the app container, is there any solution for this?

**Comment by samiranshah** [comment]
@yaichenbaum https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.FullTrustProcessLauncher?view=winrt-19041 should help you activate the full-trust component of your app. Let us know if this doesn't help.

**Comment by yaichenbaum** [comment]
@samiranshah It's an Electron app, not UWP.

**Comment by mikehearn** [comment]
We also encountered this. I can't tell if it was transient or not *but* investigation running the app outside of MSIX revealed that it was failing to start up due to a bug on our end. Once we fixed that bug and re-packaged, the access denied error went away. It seems like maybe the startup failure was being mis-translated into some other kind of error message?
