### ISSUE TITLE
REG MSIXTrace.ps1 

### ISSUE THREAD

**Issue by pk2311** [microsoft/msix-packaging#343]
Anyone able to run the script successfully? 

I am getting this error: 
PS C:\Windows\System32> C:\msixtrace.ps1
C:\msixtrace.ps1 : Parameter set cannot be resolved using the specified named parameters.
    + CategoryInfo          : InvalidArgument: (:) [msixtrace.ps1], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmbiguousParameterSet,msixtrace.ps1

**Comment by wcheng-msft** [comment]
it takes a parameter. You can use 
`.\msixtrace.ps1 -wait `
which will block that powershell, until you hit enter to stop the tracing.

Or, if you want to use the same powershell to do the repro, you can start it with
`.\msixtrace.ps1 -start`
and stop the tracing with
`.\msixtrace.ps1 -stop`

**Comment by anarvekar-msft** [comment]
Hello, if you still have any follow up questions on this, please feel free to reopen the issue.
