### ISSUE TITLE
Introduce a GUI way to install apps with restricted capabilities

### ISSUE THREAD

**Issue by saschanaz** [microsoft/msix-packaging#344]
![image](https://user-images.githubusercontent.com/3396686/82049301-602d0980-96b6-11ea-9340-4dbc41836e91.png)

Installing PowerShell with msix rejects GUI way and requires CLI way. I hope there be a GUI way too, probably with an admin privilege if this is for security.

**Comment by jvintzel** [comment]
This UX is not part of this repo.  Please file the issue in Windows Feedback hub under Apps > App Installer.
