### ISSUE TITLE
[BUG] Cannot install MSIX package on Windows 7 SP1

### ISSUE THREAD

**Issue by thibaudcomte** [microsoft/msix-packaging#345]
*Project*
MSIX SDK or Win7Msix

**Describe the bug**
Impossible to install the VLC test package on Windows 7 SP1

**To Reproduce**
- download the certificate and the msix package from https://github.com/microsoft/msix-packaging/tree/master/MsixCore/Tests
- install certificate on the Windows 7 host (certutil -addstore root APPX_TEST_ROOT.cer)
- try to install VLC-3.0.6_1.0.0.0 on the same host
We get an error 0x8bad0042 indicating an issue with the certificate... 
The install works fine on Win8.1 and Windows 10, but not on Windows 7 SP1.

**Expected behavior**
The package installs properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/21158998/82796122-4f7a5180-9e75-11ea-850e-a29990c7f323.png)

**Platform**
Windows 7 SP1

**Additional context**
None.

**Comment by dianmsft** [comment]
Hi @thibaudcomte , 0x8bad0042 - This typically means that the certificate the app was signed with is not installed. To solve this install the certificate and retry. Did you verify that the certificate is installed to the root certificate store?

**Comment by thibaudcomte** [comment]
Hi @dianmsft, thanks for your reply.
Yes, the certificate is properly installed in the root cert store (as I wrote the other day, I used the command "certutil -addstore root APPX_TEST_ROOT.cer" ;))
![image](https://user-images.githubusercontent.com/21158998/83075958-fed14700-a074-11ea-9972-73e53a769659.png)

**Comment by dianmsft** [comment]
Understood, sometimes I want to reverify. Can you also check that VLC is signed by the same certificate?

**Comment by thibaudcomte** [comment]
Ok, it seems VLC is signed with the proper certificate (I'm no expert with digital signatures though).
![image](https://user-images.githubusercontent.com/21158998/83077650-27a70b80-a078-11ea-8962-f4f4283d9481.png)

**Comment by thibaudcomte** [comment]
Mmm, I notice the certificate I installed is V3 and the msix is signed with the V2...
![image](https://user-images.githubusercontent.com/21158998/83078116-16aaca00-a079-11ea-8fc3-f2eec2eadd2a.png)

**Comment by thibaudcomte** [comment]
Apologies.
My Windows 7 image was not up to date.
Updating it and re-running certutil -addstore ... as admin fixed the issue.
I'm closing.
Thank you for your help.
