### ISSUE TITLE
Microsoft Office Add-in registration

### ISSUE THREAD

**Issue by jozefizso** [microsoft/msix-packaging#346]
**Project**
MSIX SDK

**Question**
Can application (or a library in a _modification_ package) define registry keys for a COM+ class that will be registered as an Microsoft Office Add-in?

Office add-in requires class to be registered in the `HKEY_CLASSES_ROOT` and an entry in `Software\Microsoft\Office\AppName\Addins` registry.

**Expected behavior**
A COM+ add-in (or a VSTO add-in) packaged in MSIX should be able to register itself to Microsoft Office add-ins.

**Platform**
Windows 10, Windows 7

**Comment by jvintzel** [comment]
No, today Modification Packages are required to refer to another MSIX.  Office needs to complete their move to MSIX for this to be enabled.  There is no public timeline announced for that at this time.
