### ISSUE TITLE
Rename repository to include "MSIX Core" name

### ISSUE THREAD

**Issue by Marv51** [microsoft/msix-packaging#350]
As someone following MSIX for years now, when I was looking for the repository of MSIX Core I was puzzled. Googleing (with Bing) didn't really give proper results. 

I looked at this repo multiple times, without realizing this is where all the MSIX Core action is happening.

Please update at least the Readme to make branding here more clear.

(A note that MSIX Core, refers to the heart of MSIX and not dotnet core might also be helpful to people)

**Comment by jvintzel** [comment]
MSIX Core is a variant of the stack that brings minimal functionality to downlevel devices. The goal of this repo is to open sources all aspects of build MSIX which will include more tooling over time.

**Comment by Marv51** [comment]
Point of this issue was to give feedback that the github repo structure is somewhat confusing and the README does not really explain what is where either.

MSIX consists of:
* the [VS packaging project](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net) (closed source)
* the Win10 [appinstaller](https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1) (closed source)
* the [MSIX Packaging Tool](https://docs.microsoft.com/en-us/windows/msix/packaging-tool/tool-overview) (closed source)
* the [MSIX Core SDK](https://github.com/Microsoft/msix-packaging/tree/master/MsixCore) (A sub-component of this repo)

After a significant amount of reseach into this, the difference between the MSIX Core SDK and the MSIX SDK are unclear to me. 

The MSIX Packaging APIs are a subset of the Packaging API, the readme says. If I understand correctly the MSIX Packaging APIs are the public interface of the MSIX Core SDK? While the Packaging API is the public interface of the packaging component in Windows 10.

**Comment by Marv51** [comment]
Feel free to close this, but I believe that the somewhat confusing naming is major problem for people

**Comment by Marv51** [comment]
I feel like the change of the readme (#353) makes this clearer.
