### ISSUE TITLE
[BUG] Makemsix pack creates a broken (empty) package when the given directory contains a .git folder

### ISSUE THREAD

**Issue by tnguyen63** [microsoft/msix-packaging#355]
*Project*
MSIX SDK

**Describe the bug**
When running makemsix pack with the directory argument that contains a .git, the generated MSIX package is broken as the original content in the given directory isn't in the package when inspecting the package. 

**To Reproduce**
```
cd path\to\directory\of\contents
git init
makemsix pack -d path\to\directory\of\contents -p Package.msix
```
Use 7-zip to inspect the package and we won't see the original content used to create the package.

**Expected behavior**
All the original files/binaries in the directory should be present in the package.

**Screenshots**
Directory given: 
![image](https://user-images.githubusercontent.com/66039363/87077450-fde51680-c1d7-11ea-9136-c58e80461ac0.png)

Output MSIX package:
![image](https://user-images.githubusercontent.com/66039363/87077503-12291380-c1d8-11ea-8cde-0c199982836c.png)

**Platform**
Windows 10 x64

**Additional context**
N/A

**Comment by msftrubengu** [comment]
I was not able to repro this issue, but I fixed a bug where a package that contains .git cannot be unpacked. Please reopen if you see problem again
