### ISSUE TITLE
[BUG] MSIX Package Enables System Media Transport Controls on Taskbar Preview

### ISSUE THREAD

**Issue by duke7553** [microsoft/msix-packaging#357]
*Project*
UWP App Packaged in MSIX with Full Trust Component

**Describe the bug**
In somewhat-recent Windows 10 versions, many UWP apps that are packaged in MSIX (with the Windows Application Packaging Project) to leverage a Full Trust component have media player controls visible under the taskbar thumbnail preview, despite not enabling them.  Using the relevant WinRT API from **Windows.Media** to disable/hide the controls has no effect on their visibility.  `SystemMediaTransportControls.GetForCurrentView().IsEnabled = false;`

**To Reproduce** 
1. Create a UWP application project
2. Add its reference to a Windows Application Packaging Project
3. Add another reference to a .NET Framework project to act as the FullTrust component
4. Make no changes to the **SystemMediaTransportControls** from **Windows.Media** WinRT namespace
5. Observe visible media player control buttons (aka thumbbuttons) under taskbar hover preview

**Expected behavior**
The **SystemMediaTransportControls** should be hidden from the taskbar icon thumbnail previews by default for all applications. The behavior is correct in pure UWP apps without a full trust component inside a Windows Application Packaging Project. At a minimum, the relevant WinRT API should work to hide these buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/20365014/87620279-23988100-c6ec-11ea-8b27-23b884c8b075.png)
![image](https://user-images.githubusercontent.com/20365014/87620345-4aef4e00-c6ec-11ea-9b5b-c2ce53444302.png)

**Platform**
Windows 10 v2004+ all CPU Architectures

**Additional context**
This issue is reproducible in multiple apps from the Microsoft Store that leverage the packaging project for a FullTrust component:

- Files UWP - Preview
- OneLocker Password Manager

**Comment by dpaulino** [comment]
This issue appears for [Nightingale](https://github.com/jenius-apps/nightingale-rest-api-client), which also uses a `wapproj` project

![image](https://user-images.githubusercontent.com/7649589/87625439-0315fa00-c6df-11ea-95c2-06da30729362.png)

**Comment by duke7553** [comment]
This appears to be fixed with the latest Windows dev channel flights.

**Comment by JacobDrivers** [comment]
I just opened the store and tested this myself. It is present for me as well. **Definitely** a bug.
![2021-12-04 (8)_LI](https://user-images.githubusercontent.com/44545600/144717362-a0924f6b-4488-45db-95ba-2c4ffcb72cfc.jpg)

**Comment by tritter** [comment]
This issue still persists, why has it been closed?
