### ISSUE TITLE
Installing and starting makemsix.exe

### ISSUE THREAD

**Issue by ehujair** [microsoft/msix-packaging#363]
Hello, 
I do not have experience with such things, can anyone help me to install this sdk to be abel to run makemsi.exe from commandline ? 
I have understood that I can run this command, but I dont know how to install it, have downloaded the project files, but no idea what to do then.
Target is to create msix file from some files
thanks

**Comment by msftrubengu** [comment]
Hi,

You can follow [this instructions](https://github.com/microsoft/msix-packaging#build) on how to produce makemsix.exe and msix.dll. For Windows, you should be able to clone the repo and run the makewin.cmd script that is in the top level directory with the `--pack` option. The output will be under the .vs\bin directory.

**Comment by samiranshah** [comment]
Closing for now. Please reopen if you have further questions.
