### ISSUE TITLE
Customizing Visual Studio MSIX packaging project output

### ISSUE THREAD

**Issue by mgregory22** [microsoft/msix-packaging#378]
Honestly, I don't know if this is the right place to ask this question.

I'm using a Visual Studio MSIX packaging project to create an installer on a network share for an internal application.  I'm right-clicking on the MSIX project and doing a "Create App Packages..." command.

One problem is that it's creating a directory with "_Test" at the end.  Why is it doing that and how do I get rid of it?  I just want "MyApp.MSIX_0.0.1.0", or ideally, "MyApp.0.0.1.0".

```
     Directory of I:\

    08/14/2020  09:44 AM    <DIR>          .
    08/14/2020  09:44 AM    <DIR>          ..
    08/14/2020  09:44 AM            21,312 index.html
    08/14/2020  09:23 AM               601 MyApp.MSIX.appinstaller
    08/14/2020  09:37 AM    <DIR>          MyApp.MSIX_0.0.1.0_Test
                   2 File(s)         21,913 bytes
                   3 Dir(s)  62,444,621,824 bytes free
```

I've been scouring the documentation, but I can't find anything about the directories it creates or the index.html file it generates.  I'd like to customize all that, add release notes, etc.

This is a WPF app, if that makes any difference.

**Comment by Huios** [comment]
Hi @mgregory22 

The output directory of the packages is defined in the **Microsoft.AppxPackage.Targets** file at _C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage_ (depending on your version of Visual Studio). 

If you want to remove the "_Test" suffix you can modify the lines defining the output directory. In my file it was around line 3190 - 3196:
![appx_targets](https://user-images.githubusercontent.com/5958833/91350979-567a6e00-e79c-11ea-87f0-2b48d8c07d13.PNG)

To modify the output html file, modify the **index.template.html** file in the "Landing" subdirectory - _C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Landing_ (depending on VS version).

Cheers,
Tanaka

**Comment by mgregory22** [comment]
Thank you so much!  I'm not a fan of editing the Visual Studio distribution, but if that's the only way to do it, then ok!

**Comment by stevenbrix** [comment]
@mgregory22 I don't think you need to modify the visual distribution yourself. You can set the `AppxPackageDir` property in your packaging project, and that should instruct the build system where to put the file. 

example
```xml
<PropertyGroup>
   <AppxPackageDir>I:\</AppxPackageDir>
</PropertyGroup>
```

**Comment by stevenbrix** [comment]
Sorry, I think the actual property you need to set is `AppxPackageTestDir`, and you might need to do it in a Target before the `_ComputeAppxPackageOutput` target runs:

```xml
<Target Name="_SetAppxPackageTestDir" BeforeTargets="_ComputeAppxPackageOutput">
    <PropertyGroup>
      <AppxPackageTestDir>$(AppxPackageDir)$(AppxPackageName)\</AppxPackageTestDir>
    </PropertyGroup>
</Target>
```

**Comment by mgregory22** [comment]
@stevenbrix I finally found some time to try this, but it turned out to be a terrible idea.  It blew away all of our previous versions and we had to restore the directory from a backup.  It doesn't install it in a subdirectory of the target directory, but it blows away the target directory and installs it right there!

**Comment by stevenbrix** [comment]
@mgregory22, sorry that happened 😞 

my point still stands, with MSBuild you never will need to modify VS directly. As a last resort you could copy/paste the `_ComputeAppxPackageOutput` target into a Directory.Build.targets file and make the changes you made.

**Comment by mgregory22** [comment]
@stevenbrix It's alright, I was being careless.  I need to play around with it.  I need to read more about MSBuild.

**Comment by samiranshah** [comment]
Closing for now. Please reopen if needed.

**Comment by neil-itsware** [comment]
For anyone coming in the future, the proper way to remove the `_Test` suffix in the package name is by adding this.

```xml
  <Target Name="SetAppxPackageTestDir" BeforeTargets="_ComputeAppxPackageOutput">
    <PropertyGroup>
      <AppxPackageNameNeutral>$(ProjectName)_$(AppxManifestIdentityVersion)</AppxPackageNameNeutral>
      <_AppxPackageConfiguration Condition="'$(Configuration)' != 'Release'">_$(Configuration)</_AppxPackageConfiguration>
      <AppxPackageName>$(AppxPackageNameNeutral)_$(Platform)$(_AppxPackageConfiguration)</AppxPackageName>
      <AppxPackageTestDir>$(AppxPackageDir)$(AppxPackageNameNeutral)$(_AppxPackageConfiguration)\</AppxPackageTestDir>
      <AppxPackageTestExternalPackagesDir>$(AppxPackageDir)$(AppxPackageNameNeutral)$(_AppxPackageConfiguration)\$(ExternalPackagesDir)</AppxPackageTestExternalPackagesDir>
    </PropertyGroup>
  </Target>
```
The previous solution was not working because some variables were not set

**Comment by pitMobile** [comment]
What about the index.html - Is it really required to change the template in the distribution? That doesn't make any sense to me considering I want to do all that in a CI/CD workflow in Azure DevOps.
A more logical solution would be to provide the template in the packaging project, wouldn't it? Is that possible? If not, how would I go about changing the template in the distribution from my build pipeline?
