### ISSUE TITLE
[BUG] Cannot deploy UWP app with nginx

### ISSUE THREAD

**Issue by Alkanores** [microsoft/msix-packaging#383]
*Project*
MSIX SDK

**Describe the bug**
I created my UWP app package, but ms-appinstaller shows me error when I try to install.

*(see image 1)*

in english this be something like this:
"An error occurred while parsing the application package."

if I don't open the .appinstaller, but .msix, then I can install the application

*(see image 2)*

**To Reproduce**
1. Create Universal Windows Platform project (supported 1909 and 2004 versions)
2. Pack it in Visual Studio with self-signed cert and enable autoupdate for domain uwpdeploy.test.local
3. Download nginx for Windows (x64)

4. Add this in *nginx_folder*/conf/mime.types:
```
    application/appx                                 appx;
    application/appxbundle                           appxbundle;
    application/msix                                 msix;
    application/msixbundle                           msixbundle;
    application/appinstaller                         appinstaller;
```
5. add into 'hosts' file this line: 
local ip (192.168.0.102 in my case) uwpdeploy.test.local

6. Copy all files from AppPackages to *nginx_folder*/html

**Expected behavior**
After you click on button windows open app installer and prompt you to install application

**Screenshots**
*1*
![image](https://user-images.githubusercontent.com/49155506/93513679-e12f3280-f92e-11ea-8003-94ff50e0862a.png)
*2*
![image](https://user-images.githubusercontent.com/49155506/93514031-5ef33e00-f92f-11ea-8578-49a9ad440816.png)

**Platform**
Windows 10 2004 (build 19041.508)
Windows 10 1909 (build unknown)

**Comment by Huios** [comment]
Hi @Alkanores 

Was the installation working for you before or is this the first time you're trying this? To help us diagnose the issue, can you please make a Feedback Hub submission in the **Apps > AppInstaller** category, while reproducing the error. Please also attach a copy of your .appinstaller file, the msix package, and your download page html file. And then can you please post the link to your Feedback Hub submission on here when you're done.

Thanks,
Tanaka

**Comment by Alkanores** [comment]
@Huios Thanks for answer, one more fact:

Very strange, but install from web don't work only for me, all in local network(hamachi)  can install and update my app

**Comment by Huios** [comment]
That is odd. I can't say for sure what the issue is but the Feedback Hub submission would help us investigate. After you've files the item while reproducing the error, you can try restarting your machine in case it's due to bad cached state.

**Comment by Alkanores** [comment]
How I can send feedback?

**Comment by Huios** [comment]
You can do so using the Feedback Hub app. A shortcut to open the app is the Windows Key + F. Please file it in the the **Apps > AppInstaller** category and record while reproducing the error/attempting the failing download and then submitting. 
Thanks!

**Comment by Huios** [comment]
Hi @Alkanores ,
Were you able to file the feedback? Can you please post the link, if you did.

Thanks!

**Comment by Alkanores** [comment]
@Huios 

https://aka.ms/AA9yied

**Comment by Huios** [comment]
@Alkanores 

Thanks for filing the feedback, I'm forwarding this to our devs for investigation. 

Cheers,
Tanaka

**Comment by Alkanores** [comment]
@Huios, you're welcome!

Can you also provide this feature request: https://aka.ms/AAa1x28?

Translate: 

"Add button in msix, which can create desktop shortcut for UWP sideload app"
