### ISSUE TITLE
makewin**chk.cmd implicit depended VS2017 Enterprise

### ISSUE THREAD

**Issue by josephsmeng** [Microsoft/msix-packaging#4]
in both makewin32chk.cmd and makewin64chk.cmd line 6,
the  call function are VS2017 Enterprise only, and makes  the
community version to fail.

I think it would be better to do some file check here to dectct
which version is actually installed on current machine.

**Comment by msftphil** [comment]
Do you have a pull request in mind that I can take a look at?

**Comment by tabs-not-spaces** [comment]
perhaps a solution would be to improve the programatic nature of the make script by using powershell? if so, I'm happy to put in  PR with an example that works for me...

**Comment by msftphil** [comment]
Yea, I think that's a totally reasonable way to go.  Looking forward to seeing a PR!

**Comment by AndrewPardoe** [comment]
Visual Studio 2017 includes a tool called VSWhere that is used to locate installations of Visual Studio. I would suggest using that tool. For example, here's my VCVars.cmd: it finds the latest installation of VS and calls the associated VCVars: https://gist.github.com/AndrewPardoe/689a3b969670787d5dba538bb0a48a1e.

**Comment by tabs-not-spaces** [comment]
Good idea Andrew, however if it doesn't exist for earlier versions, then it's best not to rely on it. I'm putting in a PR shortly.

**Comment by tabs-not-spaces** [comment]
have a look at the latest PR - needs testing by someone with VS Community, but should work seamlessly.
[https://github.com/Microsoft/msix-packaging/pull/6](url)

**Comment by AndrewPardoe** [comment]
VSWhere works for all versions of VS2017, and has been installed with the VS installer since VS2017 Update 1.
