### ISSUE TITLE
[BUG] Fail to install MSIX Packaging Extension to Azure DevOps

### ISSUE THREAD

**Issue by vernou** [microsoft/msix-packaging#400]
*Project*
MSIX Packaging Extension to Azure DevOps.

**Describe the bug**
The installation of MSIX Packaging Extension to Azure DevOps fail.

**To Reproduce**
1) Open marketplace from Azure DevOps Server
2) Go to page [MSIX Packaging](https://marketplace.visualstudio.com/items?itemName=MSIX.msix-ci-automation-task)
3) Click on "Get it free"

It's return on Azure DevOps Server with this error :
![image](https://user-images.githubusercontent.com/1659796/102615014-7cee5b80-4135-11eb-8df8-102f78f10e48.png)

The error message is in French, the English translation is :
> The 'method' and 'addOptionalItem1' task definition entries must belong to the same group, because they are task dependent entries with the id 'ced3bc79-ea98-4c51-8a83-ed4e3a0a77ed'.

The error message in high-left corner translation is :
> Failed to load permissions section

**Expected behavior**
The extension is installed on the collection projet

**Platform**
Azure DevOps Server's version is '17.143.28621.4'

Also I reproduce on Azure DevOps Server 2020 test instance with the version '18.170.30525.1'

**Additional context**
The installation work with other extensions. Tested with [SSIS DevOps Tools](https://marketplace.visualstudio.com/items?itemName=SSIS.ssis-devops-tools) and [Update AssemblyInfo](https://marketplace.visualstudio.com/items?itemName=sebastianlux.UpdateAssemblyInfo).

**Comment by jkocsis3** [comment]
I ran into this issue today, completely unable to install the extension.

**Comment by lechacon** [comment]
Thank you for reporting this and sorry for the delay.
This comes from the definition of the tasks' inputs [here](https://github.com/microsoft/msix-packaging/blob/bdb5d41520d51ca10aa278386a88ed74ea78585c/tools/pipelines-tasks/AppInstallerFile/task.json#L155), and something similar in the packaging task. DevOps Server seems to be doing some extra validation on the tasks that the online version does not do, and it doesn't like visibility rules for task inputs mixing input groups. Removing the groups seems to fix this, but I'm still validating it.

**Comment by jkocsis3** [comment]
@lechacon any timeline on when this will be fixed?

**Comment by lechacon** [comment]
Hi. Sorry again for the delay. This should be fixed now. Please try installing the latest version of the extension and let me know if you still have issues.

**Comment by vernou** [comment]
@lechacon, thank. I confirm the install work.
