### ISSUE TITLE
[BUG] not possible to create SelfContained=False msix

### ISSUE THREAD

**Issue by juwens** [microsoft/msix-packaging#408]
*Project*
MSIX SDK 

**Describe the bug**
I want to create a framework dependent msix (no runtime or BCL in the the MSIX).
Therefore the msix size should will be less than 5MB.
In reality though it's size is between 60-70MB and containing a whole bunch of BCL files.
I failed to find documentation on howto configure the wapproj to handle "SelfContained=False" for the referenced wpf-proj.

There is this comment from Matteo Pagani which leads me to the assumption, that it should be possible.
`the latest version of the Windows Application Packaging Project supports the framework dependent model as well. As such, it is enough to not specify the runtime identifiers in the .csproj file to generate a package which doesn't include the .NET Core runtime.` ([Source](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/packaging-a-net-core-3-0-application-with-msix/bc-p/1607381/highlight/true#M375))

**To Reproduce**

Checkout my minimal example solution: https://github.com/juwens/WpfNet5Msix
It contains:
- a stub WPF created with VS 2019, no changes, just the WPF netcoreapp template app.
- a wapproj created with vs2019, just the basics changed to reference and package the wpf proj
  - added the wpf app to applications
  - configured everything for x64
  - right click -> publish -> create App Packages...
    - Sideloading; enable automatic updates=True
    - No Skip package signing
    - app bundle: never; solution configuration: x64 -> Release x64; include pdb: True
    - upate check: everytime the application runs
    - Create

**Actual behavior**
Created msix file size is 60-70MB and contains a lot BCL files.

**Expected behavior**
Created msix file size is less than 5MB and contains no BCL files or dotnet core runtime.

**Screenshots**

**Platform**

**Additional context**

**Comment by zerodev1200** [comment]
There was an answer on [this page](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/packaging-a-net-core-3-0-application-with-msix/ba-p/386432?WT.mc_id=DT-MVP-5003978)

>Hello @juwens ,
>
>it's possible to achieve your goal but, unfortunately, this feature isn't well documented. These are the steps you have to follow:
>
> 
>
>

>1.You have to create a publish profile for your .NET app first. Right click on the .NET project (not the WAP one) and choose Publish. Follow the wizard by choosing:

>- Folder as target
>- Folder as specific target
>- Leave the default publish location

>2.Once you have finished, click on Edit under "FolderProfile" to edit the profile and choose:

>- Deployment ode: Framework-dependent
>- Target runtime: win-x86 or winx-64, based on your requirements

>3.Once you have created it, go to the WAP project and click on the .NET project name you have referenced undered Applications. Choose Properties and you will see a property called Publishing Profile. Open the dropdown and you will she .pubxml you have just created by setting up a publish profile. Be aware that this property is set on a configuration basis, e.g. if you have Debug/X86 selected in your solution it will be set only for that configuration, you can edit your project file manually or change your configuration in VS to set the other values as needed.

>Now generate the MSIX package with the WAP project, just make sure to select the same CPU architecture and configuration you have configured the publishing profile for. At the end of the process, you should get a considerably smaller MSIX package, which will contain only your executable and DLLs and not the full runtime.
>
>
>I hope it helps!

**Comment by anarvekar-msft** [comment]
Please feel free to reopen the issue if you believe the answer above didn't suffice. Closing this out.
