### ISSUE TITLE
failed to process request  8bad0031 with Win7Msix 

### ISSUE THREAD

**Issue by rahulgupta999** [Microsoft/msix-packaging#42]
Installing an .appx package with Win7MSIXInstaller.exe results in error :
failed to process request  8bad0031

Command line used: Win7MSIXInstaller.exe -AddPackage abc.appx
OS - Windows 7 SP1 (6.1 Build 7601)

**Comment by rahulgupta999** [comment]
Issue is reproduced by using both the pre-compiled and self-compiled binary

**Comment by rudyhuyn** [comment]
`Win7MSIXInstaller.exe` had some issues with certificates, fixed by the commit https://github.com/Microsoft/msix-packaging/commit/c8258683606a88244d39d192de85c7d32e00a2c3.

Can you retry with the most recent version?

Rudy

**Comment by c-don** [comment]
please reopen if you still experience the issue.
