### ISSUE TITLE
Restart App on Update

### ISSUE THREAD

**Issue by isaacrlevin** [microsoft/msix-packaging#432]
I have a WPF app that can be installed via appinstaller or the Windows Store. This app can be run in the background and is hardly restarted. Is there a way to force an app restart on update? I am aware of notifying the user of the update and asking to restart but was curious if I could just force restart after update.

**Comment by rgwood** [comment]
I haven't tried this yet, but [this doc](https://docs.microsoft.com/en-us/windows/msix/non-store-developer-updates#automatically-restarting-your-app-after-an-update) suggests that `RegisterApplicationRestart` is the way to go.

**Comment by maxkatz6** [comment]
Yes, RegisterApplicationRestart works fine.

**Comment by anarvekar-msft** [comment]
Please feel free to reopen the issue if you believe the answer above didn't suffice. Closing this out.
