### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jbyway** [microsoft/msix-packaging#437]
*Project*
MSIX SDK or Win7Msix

**Describe the bug**
Creation of CIM files from a MSIX package fails with HRESULT 0x80070050 or 0x80070003.

**To Reproduce**

- Error appears to be repeatable when original MSIX package includes long file paths nested within the file (250+ characters). Tested with VSCode package created by myself. 
- Failure message occurs after non fatal error occurs when attempting to delete the temp directory that's created to unpack the msix in to and called within the msixmgr.cpp file at "createAndAddtoCIM". 
- Temp directory that remains shows parts of the msix contents that were not deleted and presumably failed to be extracted into the cim tmp files in the destination directory. These files are above 250 characters. 
- Moving the msixmgr.exe to c:\x\msixmgr.exe and changing the temp directory to not use the GUID seems to resolve if msix files are then below ~250+ characters when extracted. Doing this by modifying the line in msixmgr.cpp "std::wstring tempDirPathString = currentDirectory + L"\\unpack";" and replacing the "+ uniqueIdString" with "\\unpack" and recompiling msixmgr.exe allowed my cim to create. 
![Screenshot 2021-03-17 143101](https://user-images.githubusercontent.com/30424593/111418472-e3d2df00-873b-11eb-93f7-ea5fe3791556.png)
![Screenshot 2021-03-17 161415](https://user-images.githubusercontent.com/30424593/111418478-e5040c00-873b-11eb-9540-16511da9fb9f.png)

**Expected behavior**
Files should be unpacked to the temp directory and subsequently placed into a CIM file. Attempting with an alternative MSIX package works when file path is shorter during unpack stage. 

**Screenshots**

**Platform**
Windows 10 20H2

**Additional context**
Attempted with NotePadPlusPlus which was successful. VSCode failed. 
[msixtrace_000001.zip](https://github.com/microsoft/msix-packaging/files/6153548/msixtrace_000001.zip)

**Comment by juanpecatala** [comment]
I have the same problem with different apps. (Visual Studio Code, Visual Studio, SQL Management Studio...)
With the vhdx format I do not have the problem, but I prefer the cim format to get best performance.
Do you have a estimated resolution date for this problem?

**Comment by PMLIO** [comment]
I have the same issue, tried converting Adobe Acrobat MSIX to CIM

**Comment by iancohn** [comment]
Same issue with Azure Data Studio

**Comment by dextraa9791** [comment]
Also having the same issue converting applications like Adobe illustrator, creating file paths like "C:\_\3909c748-1052-4783-b24e-e4878cfe7c26\AdobeIllustrator-25.2.3_1.0.1.0_x64__fzp20gpn88db2\VFS\ProgramFilesX64\Adobe\Adobe Creative Cloud Experience\js\node_modules\ref-napi\node_modules\node-addon-api\src\Release\obj\nothing\nothing.tlog", exceeding the 260 character limit.

**Comment by pratiksinha07** [comment]
https://github.com/microsoft/msix-packaging/pull/463

Issue has been fixed in the above Pull Request
