### ISSUE TITLE
[BUG] Msix Utils build fails

### ISSUE THREAD

**Issue by msftrubengu** [microsoft/msix-packaging#454]
Msix Utils tests are failing.

This is probably related to some agent configuration changes as we haven't change that code. [Build](https://dev.azure.com/ms/msix-packaging/_build/results?buildId=177205&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7bfb7e0f-549d-5929-c603-6e8046613b9e)

**Comment by msftrubengu** [comment]
More specifically: Test ProcessRunnerTest_TerminateProcess_Success

**Comment by lechacon** [comment]
I think this is a flaky test due to a race condition, not due to some agent configuration change. It just passed on a re-run. I'll look into it.

**Comment by lechacon** [comment]
This build hasn't failed in some time. I'm closing this issue.
