### ISSUE TITLE
LOB customer on premise

### ISSUE THREAD

**Issue by kevmoens** [microsoft/msix-packaging#455]
We develop line of business applications (for manufacturers) which can be hosted on-premise by a customer. We currently use click once to allow distribution of our WPF application. We use mage.exe to create the click once package so the URL works on their server.

I have looked into MSIX and the only similar flow I saw was to use MakeAppX.exe but that is part of the Windows SDK. Is there a Nuget (for MakeAppX.exe) that I could bundle with our product when we lay down the tools they use to create the MSIX package? I don't want to require each customer to install the Windows SDK. We had done similar things in the past with Microsoft downloads and since customers will be modified and sit on a version for 10+ years we have run across where customers are unable to download the packages as Microsoft has stopped support (rightfully so).

-Kevin

**Comment by anarvekar-msft** [comment]
@kevmoens Thank you for your question. No, there is no is no nuget as far as I know.

**Comment by barnson** [comment]
It's huge but you can get (parts of the) Windows SDK as a NuGet package: https://www.nuget.org/packages/Microsoft.Windows.SDK.CPP/
