### ISSUE TITLE
Azure DevOps MSIX tasks (MSIX Sign) allow parametrization of secure file reference

### ISSUE THREAD

**Issue by Styxxy** [microsoft/msix-packaging#459]
We use the Azure Devops MSIX task MSIX Sign. We have a visual build definition (not YAML).
We'd like to configure the Secure File with the certificate, rather than having the choose it already. We want this, as we have created re-usable task groups, and we can't add the MSIX Sign task because we can't configure the Secure File as a parameter, eg `$(SignCertificateSecureFileId)`. It isn't even possible to type in the drop down box.

**Comment by samiranshah** [comment]
Hi @Styxxy, this is not possible due to the limitation imposed by Azure DevOps to the dropdown (in the UI) when using a secure file, not by the MSIX task in particular. It is possible to use a variable but only on YAML (limited to global variables or template parameters), not on the UI.

**Comment by Styxxy** [comment]
@samiranshah How come the dropdown for a Service Connection can support this? Can't the same thing be allowed here?

**Comment by anarvekar-msft** [comment]
What is allowed in the UI for secure file inputs is controlled by Azure DevOps. You can submit feedback for that at https://developercommunity.visualstudio.com/search?space=21

If you still have questions on this or the previous answer did not suffice, please feel free to reopen the issue.
