### ISSUE TITLE
Is it possible to install MSIX update by HTTP link? (WinRT API)

### ISSUE THREAD

**Issue by maxkatz6** [microsoft/msix-packaging#471]
Hello.
Right now, in my application to install the update I need to download new version MSIX and install it by downloaded path with PackageManager.UpdatePackageAsync (I can't use appinstaller, since it's broken windows-wide).
Because of that I can't use advantage of differential update, and app needs to download full archive.
Is there any possibility (or maybe planned) to install/update MSIX package by its HTTP link with working differential update?

Not sure, if it's the right repository to ask this question, since it's more related to Windows API and not MSIX Core.

**Comment by anarvekar-msft** [comment]
@maxkatz6 thank you for your question. Until we get the ms-appinstaller protocol launcher issue resolved and re-enable the functionality, you are right regarding a webpage link. However, you should be able to enable automatic updating using an AppInstaller file and/or PowerShell (Set-appxpackageautoupdatesettings) with an appinstaller file. Then configure the app to update on launch.
