### ISSUE TITLE
[BUG] Language of Index File after public Application

### ISSUE THREAD

**Issue by vinhdp195** [microsoft/msix-packaging#474]
*Project*
MSIX SDK

**Describe the bug**
When the language of VisualStudio 2019 is English, the index file after building Package MSIX is English
When the language is Japanese, the index file will be Japanese
Is there any way when VS2019 English can build the index file in Japanese?

**Platform**
UWP

**Comment by samiranshah** [comment]
@edwardskrod do you have any insights on this?

**Comment by edwardskrod** [comment]
@vinhdp195

It sounds like you are asking whether we can create a feature in Visual Studio that would allow you to generate the index.html page in Japanese (or any other language), even though you are using Visual Studio in English.

Does that sound right?

**Comment by edwardskrod** [comment]
@OliaG and @SvetBonev 

I wanted to put this on your radar as a potential feature request for building MSIX with App Installer.

**Comment by edwardskrod** [comment]
@vinhdp195  Could you please submit a Feedback ticket through Developer Community:  https://developercommunity.visualstudio.com/spaces/8/index.html

**Comment by vinhdp195** [comment]
@edwardskrod
Thanks for your support
 I am understanding that for current visual studio there is no language option function for index.html is that correct?
 I will send a request as you instructed

**Comment by vinhdp195** [comment]
> @vinhdp195
> 
> It sounds like you are asking whether we can create a feature in Visual Studio that would allow you to generate the index.html page in Japanese (or any other language), even though you are using Visual Studio in English.
> 
> Does that sound right?

Right!!!
