### ISSUE TITLE
[BUG] Package project for WPF + Blazor did not include wwwroot folder

### ISSUE THREAD

**Issue by albertwoo** [microsoft/msix-packaging#488]
*Project*
MSIX SDK

**Describe the bug**
Use this project https://github.com/jorgearteiro/BlazorDesktopWPF as the base project and add a "Windows Application Packaing Project" for it and create a bundle you will see the wwwroot folder is not included

**To Reproduce**

**Expected behavior**
All the razor resource should be included

**Screenshots**

**Platform**
Visual studio 2022 preview 7

**Additional context**

**Comment by anarvekar-msft** [comment]
@jorgearteiro could you please chime in here? Is this the expected behavior for your project?

**Comment by jorgearteiro** [comment]
I never tested the packaging project, but set this property to true in your project file
    <Content Update="wwwroot\app.css">
      <CopyToOutputDirectory>True</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\index.html">
      <CopyToOutputDirectory>True</CopyToOutputDirectory>
    </Content>
I hope this helps.

**Comment by anarvekar-msft** [comment]
If the previous answer did not suffice or you still have questions on this, please feel free to reopen the issue.
