### ISSUE TITLE
Appinstaller and scale-specific asset packages - question

### ISSUE THREAD

**Issue by benstevens48** [microsoft/msix-packaging#489]
I originally posted the question below in the WindowsAppSDK repo (https://github.com/microsoft/WindowsAppSDK/discussions/1690), but was told this might be a better place (apologies if you don't accept questions).

This is a simple question about what happens if I install an msixbundle from an appinstaller file on the web rather than the Microsoft Store. The msixbundle has several asset packages for different scales (from 100 to 400) that were automatically created as separate packages in the bundle by Visual Studio. My question is what happens when the display scale changes after the initial install, so that a different scale-specific package becomes more appropriate. Will Windows automatically download and install the new scale-specific package? If so is that immediately or in a few hours time etc and does it require the appinstaller to specify automatic updates? Does it work the same for both regular and flat bundles? I could probably do a test but it would be quite time consuming and I don't know exactly how to confirm it has installed the new scale-specific package, so I was hoping someone in the know could answer here.

**Comment by joshusto** [comment]
Hi Ben,

As of 20H1, changes to the scale settings will trigger appinstaller-based automatic updates the next time an update would normally take place (see https://docs.microsoft.com/en-us/uwp/schemas/appinstallerschema/element-update-settings). This works for regular bundles and flat bundles.

Best regards,
Jonathan

**Comment by benstevens48** [comment]
Thanks for the reply. Just to clarify, what happens if the appinstaller file does not specify automatic updates? Will the scale packages be downloaded on next manual update?

**Comment by joshusto** [comment]
If the appinstaller file doesn't specify automatic updates or the user performs a manual update directly through the appxbundle, then the scale packages will be downloaded as part of the manual update.

**Comment by benstevens48** [comment]
Ok, thanks a lot for the info.
