### ISSUE TITLE
[REQUEST] Android app support

### ISSUE THREAD

**Issue by upintheairsheep** [microsoft/msix-packaging#493]
Can you make msix packages that contain an apk and obbs that install it to a PC with WSA?

**Comment by anarvekar-msft** [comment]
Thank you for your question. Can you explain more what you are trying to do?

**Comment by upintheairsheep** [comment]
To install both chromium based browser extensions and Android apps via WSA. Android apps will be useful for business testing and/or Android tools, browser ditto

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/msix-packaging/issues/493#issuecomment-999275069

@upintheairsheep, this seems like something that should have been posted as a https://github.com/microsoft/msix-packaging/discussions/new?category=q-a and then filed separately an FR when you have all the information you need, because I have no idea what you're asking. Could you elaborate?

**Comment by upintheairsheep** [comment]
WSA is being discontinued, so closed.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microsoft/msix-packaging/issues/493#issuecomment-2159189429

@upintheairsheep, I suppose that https://github.com/waydroid/waydroid/issues/217#issuecomment-1992925041 doesn't change anything, since it's not 1st-party?

**Comment by upintheairsheep** [comment]
> > [#493 (comment)](https://github.com/microsoft/msix-packaging/issues/493#issuecomment-2159189429)
> 
> @upintheairsheep, I suppose that [waydroid/waydroid#217 (comment)](https://github.com/waydroid/waydroid/issues/217#issuecomment-1992925041) doesn't change anything, since it's not 1st-party?

Yes it does not, unless MS integrates it officially
