### ISSUE TITLE
[BUG] VS 2022

### ISSUE THREAD

**Issue by surajraja** [microsoft/msix-packaging#499]
*Project*
MSIX SDK or Win7Msix

**Describe the bug**
we are using vs 2022 and when running the build it defaults to

MSBuild_4.0_x64
MSBuild_4.0
C:\Windows\Microsoft.NET\Framework64\v4.0.30319\

and not to

F:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\
MSBuild
MSBuild_17.0

so pakcage fails

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

**Additional context**

**Comment by anarvekar-msft** [comment]
@surajraja Thank you for your post. If your question is about the packaging extension, I think this post here might be able to help you: https://github.com/microsoft/msix-packaging/issues/491

**Comment by anarvekar-msft** [comment]
Hi @surajraja if you have any following questions, please feel free to reopen the issue.
