### ISSUE TITLE
VS2017 includes the v140 toolset--why are you recommending Chocolatey?

### ISSUE THREAD

**Issue by AndrewPardoe** [Microsoft/msix-packaging#5]
The README suggests that if you can't find the v140 toolset you should install the Build Tools from Chocolatey and explicitly remove the v141 toolset. This raises a number of questions:

1. Why does new code only work with an old toolset? Is there a particular dependency or bug in your code preventing you from keeping your compiler toolset current? Have you reached out to the MSVC team to try to resolve this issue?
2. Why are your recommending that developers install the Build Tools if they are already using VS2017? The VS2017 installer includes the v140 toolset.
3. Why are you recommending that developers install the Build Tools through Chocolatey rather than from the supported path (e.g., https://aka.ms/BuildTools)? Who maintains the Chocolately version of the Build Tools? Are they current? Are they serviceable? Do they present a EULA?

Feel free to contact me directly through email if you prefer.

**Comment by msftphil** [comment]
Taking offline.

**Comment by AndrewPardoe** [comment]
Thanks! Feel free to delete the issue if you like.
