### ISSUE TITLE
[BUG] MSIXMGR fails to convert msixbundle to vhdx format with error HRESULT 0x8000ffff

### ISSUE THREAD

**Issue by JimMoyle** [microsoft/msix-packaging#516]
*Project*
MSIX SDK or Win7Msix

**Describe the bug**
This happens with many packages, but you can reproduce using the windows terminal msix bundle

Failed with HRESULT 0x8000ffff when trying to unpack Microsoft.WindowsTerminal_Win11_1.12.10983.0_8wekyb3d8bbwe.msixbundle

**To Reproduce**

Download The Windows Terminal via WinGet

Run the following msix manager command:
& 'C:\Program Files\MSIXMGR\msixmgr.exe' -Unpack -packagePath $fileName -destination $destinationPath -applyacls -create -vhdSize 100 -filetype "vhdx" -rootDirectory apps

**Expected behavior**
A vhdx with the correct app inside.
The minimum I would expect is an actionable error statement.

**Screenshots**

**Platform**
Windows 11

**Additional context**

**Comment by vishmicrosoft** [comment]
Issue was with pseudo locales used in msixbundle apps
