### ISSUE TITLE
[BUG] Unable to attach to CoreCLR. Error while Debugging installed app package

### ISSUE THREAD

**Issue by KWodarczyk** [microsoft/msix-packaging#560]
*Project*
MSIX SDK

**Describe the bug**
I am trying to debug my Test WinUI3 packaged app using Debug=>Other Debug Targets.
It starts the app but i get "Unable to attach to CoreCLR. A debug component is not installed" error popup

**Screenshots**
![image](https://user-images.githubusercontent.com/5243438/213300308-b66f7f50-6b2e-48bb-987b-fb8638f60e65.png).

**Platform**
Windows 11

**Additional context**

**Comment by anarvekar-msft** [comment]
Hello, your question might be better answered in this repo instead- https://github.com/microsoft/microsoft-ui-xaml

This repo is for MSIX SDK related questions.

**Comment by trympet** [comment]
Relevant: https://developercommunity.visualstudio.com/t/Attaching-to-Appx-from-Microsoft-Store-/1271468?moreInfo=true&viewtype=all
