### ISSUE TITLE
Email listed in SUPPORT.md is wrong

### ISSUE THREAD

**Issue by DRSchlaubi** [microsoft/msix-packaging#588]
when e-mailing [MSIXPackagingOSSCustomerQs@service.microsoft.com](mailto:MSIXPackagingOSSCustomerQs@service.microsoft.com) that email bounces back with

`550 5.4.1 Recipient address rejected: Access denied. AS(201806281) [DM3NAM06FT003.Eop-nam06.prod.protection.outlook.com 2023-06-25T21:00:46.606Z 08DB7494392B01B5]`

**Comment by anarvekar-msft** [comment]
Thank you for your comment, fixed!
