### ISSUE TITLE
[BUG] Cant sign dlls exes inside my MSIX when creating a published package to microsfot store

### ISSUE THREAD

**Issue by jmecosta** [microsoft/msix-packaging#595]
Hi,

I dont want to unpack the package, repack everything after signing. it doesnt feel natural.... Whats the proper way to sign DLLs and Exes inside my msix package... 

Is there a easy way  to do it while building the package? 

thanks 
Jorge Costa

**Comment by florelis** [comment]
I don't think you can sign the DLLs and EXEs at the same time you sign the whole package. You have to sign the files before you create the package with makeappx (which you may not be calling directly).

There may be ways to avoid having to unpack and repack depending on how you are building the package. For example, if you are using MSBuild (projects defined in .vcxproj or .csproj), you can add a post-build "target" to your project to sign the files after compiling them, but before it gets to the target that creates the package.

**Comment by DrusTheAxe** [comment]
+1

**Comment by jmecosta** [comment]
@florelis that can work at the moment, because we still have a certificate around and we can use sign tool. But very soon those certificates will no longer be issued by authorities... and we need to send the files to some server to get signed... I dont think its a good idea to hold the build process to send tons of dlls over network to be signed. Generally it would be better if this would be provided by Microsoft store.  But maybe thats another side question. 

Thanks for the tip.
