### ISSUE TITLE
MSI is not signed

### ISSUE THREAD

**Issue by rido-min** [Microsoft/msix-packaging#68]
The release https://github.com/Microsoft/msix-packaging/releases/tag/Win7MsixInstaller-preview is not signed

![image](https://user-images.githubusercontent.com/14916339/54306342-6392a580-4586-11e9-8b07-3ac9ec4e4f23.png)

![image](https://user-images.githubusercontent.com/14916339/54306637-0d723200-4587-11e9-8f44-c8108c4c8a27.png)

**Comment by wcheng-msft** [comment]
Updated. It is now signed.
