### ISSUE TITLE
Must a UWP App Package Using MSIX be sideloaded

### ISSUE THREAD

**Issue by VagueGit** [Microsoft/msix-packaging#7]
Before I get too heavily into MSIX, if we package a UWP app using MSIX will customers be able to download and install without their machine being configured for sideloading? In other words can we distribute a UWP app packaged with MSIX just as freely as we previously distributed Win32 apps?

**Comment by c-don** [comment]
@VagueGit - Customers will need to have their machine in sideload mode if the packages are not store signed. You are free to distribute the UWP app packages in a manner that fits your needs. Although, we do recommend the Microsoft Store for UWP app distribution.

**Comment by VagueGit** [comment]
Thanks @c-don that kills UWP for ISVs then.

**Comment by jvintzel** [comment]
Sideloading is enabled by default on Windows 10 Home and Pro since 10586.

**Comment by VagueGit** [comment]
Just to be clear ... if we package a UWP app using MSIX then customers can download the app from our website and just follow the prompts to install and as long as they have 10586 or later the user experience will be just like any app install ... they won't have to configure Windows?

**Comment by gulshan** [comment]
Will the "S Mode" be on by default in the upcoming Windows version?

**Comment by msftphil** [comment]
@gulshan, This is not an appropriate forum to discuss future details, plans, or features for Windows.

**Comment by msftphil** [comment]
@VagueGit.  Yes, if you package a UWP app using either Appx or MSIX and it is signed by a certificate that chains to a trusted root authority on the machine, then customers can download the app from a website and follow the prompts to install as long as they have 10586 or later.

**Comment by msftphil** [comment]
@VagueGit,  If you have further questions that you'd like to follow-up on, please reach out to MSIXPackagingOSSCustomerQs@service.microsoft.com for further support.
